### ISSUE TITLE
参加申請のフォーム画面の入力結果を集計した値をサイトに表示する

### ISSUE THREAD

**Issue by KoinoEngineering** [KoinoEngineering/one-click-hugo-cms#13]
## 関連Issue
- connect fhs46-fujimoto/one-click-hugo-cms#5

## 概要
- 関連Issue参照

**Comment by fujimoto-lab** [comment]
集計結果は、手動でCMSから入力する方式とする。

**Comment by KoinoEngineering** [comment]
↓のIssueに紐づけて対応するためこちらはクローズ
https://github.com/fhs46-fujimoto/one-click-hugo-cms/issues/5
